version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - python -m unittest discover # Optional: Run tests
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - '**/*'
